export const productsTableData = {
	header: [
		{id: 1, title: "Name"},
		{id: 2, title: "Category"},
		{id: 3, title: "Price"},
		{id: 4, title: "Quantity"},
		{id: 5, title: "Active"},
	],
	row: [
		{id: 1, title: "A Walk Amongst Friends - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 2, title: "Braies Lake - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 3, title: "Fall Glow - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 4, title: "First Snow - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 5, title: "Lago di Braies - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 6, title: "Indian Citizen", category: "Canvas Print", quantity: 10, price: 10},
		{id: 7, title: "Lago di Sorapis - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 8, title: "Never Stop Changing - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 9, title: "Reaching - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 10, title: "Morain Lake - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 11, title: "Yosemite - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 12, title: "Lago di Sorapis - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 13, title: "Never Stop Changing - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
		{id: 14, title: "Reaching - Canvas Print", category: "Canvas Print", quantity: 10, price: 10},
	],
};
export const ordersTableData = {
	header: [
		{id: 1, title: "ID"},
		{id: 2, title: "Reference"},
		{id: 3, title: "Customer"},
		{id: 4, title: "Total"},
		{id: 5, title: "Payment"},
		{id: 6, title: "Status"},
		{id: 7, title: "Date"},
	],
	row: [
		{
			id: 1,
			reference: "35a4dbc6",
			customer: "Dollie Bullock",
			Total: 10,
			payment: "Credit Card",
			status: "not-paid",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 2,
			reference: "70d4d7d0",
			customer: "Dollie Bullock",
			Total: 24,
			payment: "Check",
			status: "awaiting",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 3,
			reference: "2003479c",
			customer: "Dollie Bullock",
			Total: 85,
			payment: "Bank Ware",
			status: "preparing",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 4,
			reference: "09f5443b",
			customer: "Dollie Bullock",
			Total: 83,
			payment: "Pay Pal",
			status: "error",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 5,
			reference: "35a4dbc6",
			customer: "Dollie Bullock",
			Total: 77,
			payment: "Credit Card",
			status: "delivered",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 6,
			reference: "35a4dbc6",
			customer: "Dollie Bullock",
			Total: 10,
			payment: "Credit Card",
			status: "not-paid",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 7,
			reference: "70d4d7d0",
			customer: "Dollie Bullock",
			Total: 24,
			payment: "Check",
			status: "awaiting",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 8,
			reference: "2003479c",
			customer: "Dollie Bullock",
			Total: 85,
			payment: "Bank Ware",
			status: "preparing",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 9,
			reference: "09f5443b",
			customer: "Dollie Bullock",
			Total: 83,
			payment: "Pay Pal",
			status: "error",
			date: "2015/04/10 07:03:52",
		},
		{
			id: 10,
			reference: "35a4dbc6",
			customer: "Dollie Bullock",
			Total: 77,
			payment: "Credit Card",
			status: "delivered",
			date: "2015/04/10 07:03:52",
		},
	],
};
